using System.ComponentModel;

namespace Bixa.Backend.Models.Enums;

public enum BudgetaryItemEnum
{
    #region RRHH
    [Description("PERSONAL DE PLANTA")]
    [LongValue(2152101000)]
    PERSONAL_DE_PLANTA,

    [Description("PERSONAL A CONTRATA")]
    [LongValue(2152102000)]
    PERSONAL_A_CONTRATA,

    [Description("HONORARIOS A SUMA ALZADA - PERSONAS NATURALES")]
    [LongValue(2152103001)]
    HONORARIOS_A_SUMA_ALZADA_PERSONAS_NATURALES,

    [Description("SUPLENCIAS Y REEMPLAZOS")]
    [LongValue(2152103005)]
    SUPLENCIAS_Y_REEMPLAZOS,

    [Description("OTRAS PRESTACIONES DE PERSONAL")]
    [LongValue(2152103999)]
    OTRAS_PRESTACIONES_DE_PERSONAL,
    #endregion RRHH

    #region BIENES DE SERVICIO Y CONSUMO
    [Description("ALIMENTOS Y BEBIDAS")]
    [LongValue(2152201000)]
    ALIMENTOS_Y_BEBIDAS,

    [Description("TEXTILES, VESTUARIO Y CALZADO")]
    [LongValue(2152202000)]
    TEXTILES_VESTUARIO_Y_CALZADO,

    [Description("TEXTILES Y ACABADOS TEXTILES")]
    [LongValue(2152202001)]
    TEXTILES_Y_ACABADOS_TEXTILES,

    [Description("VESTUARIO, ACCESORIOS Y PRENDAS DIVERSAS")]
    [LongValue(2152202002)]
    VESTUARIO_ACCESORIOS_Y_PRENDAS_DIVERSAS,

    [Description("CALZADO")]
    [LongValue(2152202003)]
    CALZADO,

    [Description("COMBUSTIBLES Y LUBRICANTES")]
    [LongValue(2152203000)]
    COMBUSTIBLES_Y_LUBRICANTES,

    [Description("PARA VEHICULOS")]
    [LongValue(2152203001)]
    COMBUSTIBLES_PARA_VEHICULOS,

    [Description("PARA MAQUINARIAS, EQUIPOS DE PRODUCCION, TRACCION Y ELEVACION")]
    [LongValue(2152203002)]
    COMBUSTIBLES_PARA_MAQUINARIAS_EQUIPOS_DE_PRODUCCION_TRACCION_Y_ELEVACION,

    [Description("PARA CALEFACCION")]
    [LongValue(2152203003)]
    COMBUSTIBLES_PARA_CALEFACCION,

    [Description("OTROS COMBUSTIBLES Y LUBRICANTES")]
    [LongValue(2152203999)]
    OTROS_COMBUSTIBLES_Y_LUBRICANTES,

    [Description("MATERIALES DE USO O CONSUMO")]
    [LongValue(2152204000)]
    MATERIALES_DE_USO_O_CONSUMO,

    [Description("MATERIALES DE OFICINA")]
    [LongValue(2152204001)]
    MATERIALES_DE_OFICINA,

    [Description("TEXTOS Y OTROS MATERIALES DE ENSENANZA")]
    [LongValue(2152204002)]
    TEXTOS_Y_OTROS_MATERIALES_DE_ENSENANZA,

    [Description("PRODUCTOS QUIMICOS")]
    [LongValue(2152204003)]
    PRODUCTOS_QUIMICOS,

    [Description("PRODUCTOS FARMACEUTICOS")]
    [LongValue(2152204004)]
    PRODUCTOS_FARMACEUTICOS,

    [Description("MATERIALES Y UTILES QUIRURGICOS")]
    [LongValue(2152204005)]
    MATERIALES_Y_UTILES_QUIRURGICOS,

    [Description("FERTILIZANTES, INSECTICIDAS, FUNGICIDAS Y OTROS")]
    [LongValue(2152204006)]
    FERTILIZANTES_INSECTICIDAS_FUNGICIDAS_Y_OTROS,

    [Description("MATERIALES Y UTILES DE ASEO")]
    [LongValue(2152204007)]
    MATERIALES_Y_UTILES_DE_ASEO,

    [Description("MENAJE PARA OFICINA, CASINO Y OTROS")]
    [LongValue(2152204008)]
    MENAJE_PARA_OFICINA_CASINO_Y_OTROS,

    [Description("INSUMOS, REPUESTOS Y ACCESORIOS COMPUTACIONALES")]
    [LongValue(2152204009)]
    INSUMOS_REPUESTOS_Y_ACCESORIOS_COMPUTACIONALES,

    [Description("MATERIALES PARA MANTENIMIENTO Y REPARACIONES DE INMUEBLES")]
    [LongValue(2152204010)]
    MATERIALES_PARA_MANTENIMIENTO_Y_REPARACIONES_DE_INMUEBLES,

    [Description("REPUESTOS Y ACCESORIOS PARA MANTENIMIENTO Y REPARACIONES DE VEHICULOS")]
    [LongValue(2152204011)]
    REPUESTOS_Y_ACCESORIOS_PARA_MANTENIMIENTO_Y_REPARACIONES_DE_VEHICULOS,

    [Description("OTROS MATERIALES, REPUESTOS Y UTILES DIVERSOS")]
    [LongValue(2152204012)]
    OTROS_MATERIALES_REPUESTOS_Y_UTILES_DIVERSOS,

    [Description("EQUIPOS MENORES")]
    [LongValue(2152204013)]
    EQUIPOS_MENORES,

    [Description("PRODUCTOS ELABORADOS DE CUERO, CAUCHO Y PLASTICO")]
    [LongValue(2152204014)]
    PRODUCTOS_ELABORADOS_DE_CUERO_CAUCHO_Y_PLASTICO,

    [Description("PRODUCTOS AGROPECUARIOS Y FORESTALES")]
    [LongValue(2152204015)]
    PRODUCTOS_AGROPECUARIOS_Y_FORESTALES,

    [Description("MATERIAS PRIMAS Y SEMIELABORADAS")]
    [LongValue(2152204016)]
    MATERIAS_PRIMAS_Y_SEMIELABORADAS,

    [Description("OTROS MATERIALES DE CONSUMO")]
    [LongValue(2152204999)]
    OTROS_MATERIALES_DE_CONSUMO,

    [Description("ELECTRICIDAD")]
    [LongValue(2152205001)]
    ELECTRICIDAD,

    [Description("AGUA")]
    [LongValue(2152205002)]
    AGUA,

    [Description("GAS")]
    [LongValue(2152205003)]
    GAS,

    [Description("CORREO")]
    [LongValue(2152205004)]
    CORREO,

    [Description("TELEFONIA FIJA")]
    [LongValue(2152205005)]
    TELEFONIA_FIJA,

    [Description("TELEFONIA CELULAR")]
    [LongValue(2152205006)]
    TELEFONIA_CELULAR,

    [Description("ACCESO A INTERNET")]
    [LongValue(2152205007)]
    ACCESO_A_INTERNET,

    [Description("ENLACES DE TELECOMUNICACIONES")]
    [LongValue(2152205008)]
    ENLACES_DE_TELECOMUNICACIONES,

    [Description("OTROS SERVICIOS BASICOS")]
    [LongValue(2152205999)]
    OTROS_SERVICIOS_BASICOS,

    [Description("MANTENIMIENTO Y REPARACION DE EDIFICACIONES")]
    [LongValue(2152206001)]
    MANTENIMIENTO_Y_REPARACION_DE_EDIFICACIONES,

    [Description("MANTENIMIENTO Y REPARACION DE VEHICULOS")]
    [LongValue(2152206002)]
    MANTENIMIENTO_Y_REPARACION_DE_VEHICULOS,

    [Description("MANTENIMIENTO Y REPARACION MOBILIARIOS Y OTROS")]
    [LongValue(2152206003)]
    MANTENIMIENTO_Y_REPARACION_MOBILIARIOS_Y_OTROS,

    [Description("MANTENIMIENTO Y REPARACION DE MAQUINAS Y EQUIPOS DE OFICINA")]
    [LongValue(2152206004)]
    MANTENIMIENTO_Y_REPARACION_DE_MAQUINAS_Y_EQUIPOS_DE_OFICINA,

    [Description("MANTENIMIENTO Y REPARACION DE MAQUINARIA Y EQUIPOS DE PRODUCCION")]
    [LongValue(2152206005)]
    MANTENIMIENTO_Y_REPARACION_DE_MAQUINARIA_Y_EQUIPOS_DE_PRODUCCION,

    [Description("MANTENIMIENTO Y REPARACION DE OTRAS MAQUINARIAS Y EQUIPOS")]
    [LongValue(2152206006)]
    MANTENIMIENTO_Y_REPARACION_DE_OTRAS_MAQUINARIAS_Y_EQUIPOS,

    [Description("MANTENIMIENTO Y REPARACION DE EQUIPOS INFORMATICOS")]
    [LongValue(2152206007)]
    MANTENIMIENTO_Y_REPARACION_DE_EQUIPOS_INFORMATICOS,

    [Description("OTROS MANTENIMIENTOS Y REPARACIONES")]
    [LongValue(2152206999)]
    OTROS_MANTENIMIENTOS_Y_REPARACIONES,

    [Description("SERVICIOS DE PUBLICIDAD")]
    [LongValue(2152207001)]
    SERVICIOS_DE_PUBLICIDAD,

    [Description("SERVICIOS DE IMPRESION")]
    [LongValue(2152207002)]
    SERVICIOS_DE_IMPRESION,

    [Description("SERVICIOS DE ENCUADERNACION Y EMPASTE")]
    [LongValue(2152207003)]
    SERVICIOS_DE_ENCUADERNACION_Y_EMPASTE,

    [Description("OTROS SERVICIOS DE PUBLICIDAD Y DIFUSION")]
    [LongValue(2152207999)]
    OTROS_SERVICIOS_DE_PUBLICIDAD_Y_DIFUSION,

    [Description("SERVICIOS DE ASEO")]
    [LongValue(2152208001)]
    SERVICIOS_DE_ASEO,

    [Description("SERVICIOS DE VIGILANCIA")]
    [LongValue(2152208002)]
    SERVICIOS_DE_VIGILANCIA,

    [Description("PASAJES, FLETES Y BODEGAJES")]
    [LongValue(2152208007)]
    PASAJES_FLETES_Y_BODEGAJES,

    [Description("SALAS CUNAS Y/O JARDINES INFANTILES")]
    [LongValue(2152208008)]
    SALAS_CUNAS_Y_O_JARDINES_INFANTILES,

    [Description("SERVICIOS DE PAGO Y COBRANZA")]
    [LongValue(2152208009)]
    SERVICIOS_DE_PAGO_Y_COBRANZA,

    [Description("SERVICIOS DE SUSCRIPCION Y SIMILARES")]
    [LongValue(2152208010)]
    SERVICIOS_DE_SUSCRIPCION_Y_SIMILARES,

    [Description("OTROS SERVICIOS GENERALES")]
    [LongValue(2152208999)]
    OTROS_SERVICIOS_GENERALES,

    [Description("ARRIENDO DE TERRENOS")]
    [LongValue(2152209001)]
    ARRIENDO_DE_TERRENOS,

    [Description("ARRIENDO DE EDIFICIOS")]
    [LongValue(2152209002)]
    ARRIENDO_DE_EDIFICIOS,

    [Description("ARRIENDO DE VEHICULOS")]
    [LongValue(2152209003)]
    ARRIENDO_DE_VEHICULOS,

    [Description("ARRIENDO DE MOBILIARIOS Y OTROS")]
    [LongValue(2152209004)]
    ARRIENDO_DE_MOBILIARIOS_Y_OTROS,

    [Description("ARRIENDO DE MAQUINAS Y EQUIPOS")]
    [LongValue(2152209005)]
    ARRIENDO_DE_MAQUINAS_Y_EQUIPOS,

    [Description("ARRIENDO DE EQUIPOS INFORMATICOS")]
    [LongValue(2152209006)]
    ARRIENDO_DE_EQUIPOS_INFORMATICOS,

    [Description("OTROS ARRIENDOS")]
    [LongValue(2152209999)]
    OTROS_ARRIENDOS,

    [Description("SERVICIOS FINANCIEROS Y DE SEGUROS")]
    [LongValue(2152210000)]
    SERVICIOS_FINANCIEROS_Y_DE_SEGUROS,

    [Description("GASTOS FINANCIEROS POR COMPRA Y VENTA DE TITULOS Y VALORES")]
    [LongValue(2152210001)]
    GASTOS_FINANCIEROS_POR_COMPRA_Y_VENTA_DE_TITULOS_Y_VALORES,

    [Description("PRIMAS Y GASTOS DE SEGUROS")]
    [LongValue(2152210002)]
    PRIMAS_Y_GASTOS_DE_SEGUROS,

    [Description("SERVICIOS DE GIROS Y REMESAS")]
    [LongValue(2152210003)]
    SERVICIOS_DE_GIROS_Y_REMESAS,

    [Description("ESTUDIOS E INVESTIGACIONES")]
    [LongValue(2152211001)]
    ESTUDIOS_E_INVESTIGACIONES,

    [Description("CURSOS DE CAPACITACION")]
    [LongValue(2152211002)]
    CURSOS_DE_CAPACITACION,

    [Description("SERVICIOS INFORMATICOS")]
    [LongValue(2152211003)]
    SERVICIOS_INFORMATICOS,

    [Description("OTROS SERVICIOS TECNICOS Y PROFESIONALES")]
    [LongValue(2152211999)]
    OTROS_SERVICIOS_TECNICOS_Y_PROFESIONALES,


    [Description("GASTOS MENORES")]
    [LongValue(2152212002)]
    GASTOS_MENORES,

    [Description("PRESTACIONES SOCIALES DEL EMPLEADOR")]
    [LongValue(2152303000)]
    PRESTACIONES_SOCIALES_DEL_EMPLEADOR,

    [Description("INDEMNIZACION CARGO FISCAL")]
    [LongValue(2152303001)]
    INDEMNIZACION_CARGO_FISCAL,

    [Description("OTRAS INDEMNIZACIONES")]
    [LongValue(2152303004)]
    OTRAS_INDEMNIZACIONES,
    #endregion BIENES DE SERVICIO Y CONSUMO

    #region OTROS 
    [Description("DEVOLUCIONES PPTO.")]
    [LongValue(2152601001)]
    DEVOLUCIONES_PPTO,

    [Description("DEVOLUCIONES CONVENIOS")]
    [LongValue(2152601002)]
    DEVOLUCIONES_CONVENIOS,

    [Description("C X P INICIATIVAS DE INVERSION")]
    [LongValue(2153100000)]
    C_X_P_INICIATIVAS_DE_INVERSION,

    [Description("ESTUDIOS BASICOS")]
    [LongValue(2153101000)]
    ESTUDIOS_BASICOS,

    [Description("PROYECTOS")]
    [LongValue(2153102000)]
    PROYECTOS,

    [Description("DEUDA FLOTANTE")]
    [LongValue(2153407000)]
    DEUDA_FLOTANTE,

    #endregion OTROS

    #region MOBILIARIO MAQUINARIA ETC
    [Description("TERRENOS")]
    [LongValue(2152901000)]
    TERRENOS,

    [Description("EDIFICIOS")]
    [LongValue(2152902000)]
    EDIFICIOS,

    [Description("VEHICULOS")]
    [LongValue(2152903000)]
    VEHICULOS,

    [Description("MAQUINAS Y EQUIPOS")]
    [LongValue(2152905000)]
    MAQUINAS_Y_EQUIPOS,

    [Description("EQUIPOS INFORMATICOS COMPUTACIONALES Y PERIFIERICOS")]
    [LongValue(2152906000)]
    EQUIPOS_INFORMATICOS_COMPUTACIONALES_Y_PERIFERICOS,

    [Description("PROGRAMAS INFORMATICOS/SISTEMAS DE INFORMACION")]
    [LongValue(2152907000)]
    PROGRAMAS_INFORMATICOS_SISTEMAS_DE_INFORMACION,
    #endregion MOBILIARIO MAQUINARIA ETC



}

[AttributeUsage(AttributeTargets.Field)]
public class LongValueAttribute : Attribute
{
    public long Value { get; }

    public LongValueAttribute(long value)
    {
        Value = value;
    }
}