// <auto-generated />
using System;
using Bixa.Backend.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bixa.Backend.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Aprobacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AprobadorCi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedByCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int>("TramiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AprobadorCi");

                    b.HasIndex("ModifiedByCi");

                    b.HasIndex("TramiteId");

                    b.ToTable("Aprobaciones");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Notifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModifiedByCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCi")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedByCi");

                    b.HasIndex("UserCi");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Solicitudes.SolicitudVacaciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Desde")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasTotales")
                        .HasColumnType("int");

                    b.Property<DateTime>("Hasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TramiteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TramiteId")
                        .IsUnique();

                    b.ToTable("SolicitudesVacaciones");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.SoporteChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModifiedByCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RespondidoPorCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedByCi");

                    b.HasIndex("RespondidoPorCi")
                        .HasDatabaseName("IX_SoporteChat_RespondidoPorCi");

                    b.HasIndex("UserCi")
                        .HasDatabaseName("IX_SoporteChat_UserCi");

                    b.HasIndex("UsersId");

                    b.ToTable("SoporteChats");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.TipoTramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TipoTramite", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Anticipo de Utilidades"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Prestaciones Sociales"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Préstamo Prestaciones"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Vacaciones"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Dia Especial"
                        });
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Tramite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedByCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TipoTramiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCi")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedByCi");

                    b.HasIndex("TipoTramiteId");

                    b.HasIndex("UserCi");

                    b.ToTable("Tramites");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.UserRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Empleado"
                        });
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdUserRol")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedByCi")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Ci")
                        .IsUnique();

                    b.HasIndex("IdUserRol");

                    b.HasIndex("ModifiedByCi");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 74,
                            Ci = "10.486.165",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "MAGLENY",
                            IdUserRol = 1,
                            IsActive = true,
                            LastName = "MATHEUS",
                            PasswordHash = "6n6SwrZf48UTEsrxT17QQ53bIe3xGLq+mqTYJiK9OpPiI3IlMy+B+n9ZVsFF9u15",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Models.SolicitudesChats", b =>
                {
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Respondido")
                        .HasColumnType("int");

                    b.Property<string>("UserCi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Aprobacion", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "Aprobador")
                        .WithMany("Aprobaciones")
                        .HasForeignKey("AprobadorCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Aprobacion_ModifiedUser");

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Tramite", "Tramite")
                        .WithMany("Aprobaciones")
                        .HasForeignKey("TramiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aprobador");

                    b.Navigation("ModifiedUser");

                    b.Navigation("Tramite");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Notifications", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Notifications_ModifiedUser");

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "User")
                        .WithMany("Notification")
                        .HasForeignKey("UserCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Solicitudes.SolicitudVacaciones", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.Tramite", "Tramite")
                        .WithOne()
                        .HasForeignKey("Bixa.Backend.DataAccess.Entities.Solicitudes.SolicitudVacaciones", "TramiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tramite");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.SoporteChat", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_SoporteChat_ModifiedUser");

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "RespondidoPor")
                        .WithMany()
                        .HasForeignKey("RespondidoPorCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", null)
                        .WithMany("SoporteChats")
                        .HasForeignKey("UsersId");

                    b.Navigation("ModifiedUser");

                    b.Navigation("RespondidoPor");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Tramite", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Tramite_ModifiedUser");

                    b.HasOne("Bixa.Backend.DataAccess.Entities.TipoTramite", "TipoTramite")
                        .WithMany()
                        .HasForeignKey("TipoTramiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "User")
                        .WithMany("Tramites")
                        .HasForeignKey("UserCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedUser");

                    b.Navigation("TipoTramite");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Users", b =>
                {
                    b.HasOne("Bixa.Backend.DataAccess.Entities.UserRol", "UserRol")
                        .WithMany()
                        .HasForeignKey("IdUserRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Users_UserRols_IdUserRol");

                    b.HasOne("Bixa.Backend.DataAccess.Entities.Users", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedByCi")
                        .HasPrincipalKey("Ci")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Users_ModifiedUser");

                    b.Navigation("ModifiedUser");

                    b.Navigation("UserRol");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Tramite", b =>
                {
                    b.Navigation("Aprobaciones");
                });

            modelBuilder.Entity("Bixa.Backend.DataAccess.Entities.Users", b =>
                {
                    b.Navigation("Aprobaciones");

                    b.Navigation("Notification");

                    b.Navigation("SoporteChats");

                    b.Navigation("Tramites");
                });
#pragma warning restore 612, 618
        }
    }
}
